# Generated by Django 6.0.4 on 2026-04-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('id_football_data', models.IntegerField(blank=True, help_text='ID en football-data.org', null=True)),
                ('escudo_url', models.URLField(blank=True, default='')),
                ('estadio', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_football_data', models.IntegerField(help_text='ID en football-data.org', unique=True)),
                ('goles_local', models.IntegerField(blank=True, null=True)),
                ('goles_visitante', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('jornada', models.IntegerField(blank=True, null=True)),
                ('competicion', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(choices=[('FINISHED', 'Finalizado'), ('SCHEDULED', 'Programado'), ('LIVE', 'En directo'), ('IN_PLAY', 'En juego'), ('PAUSED', 'Pausado'), ('POSTPONED', 'Aplazado'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='rendimiento.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='rendimiento.equipo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
